from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func
from .database import Base

class Complaint(Base):
    __tablename__ = "complaints"

    id = Column(String, primary_key=True, index=True)
    user_details = Column(String, index=True)
    description = Column(Text)
    category = Column(String, index=True)  # Fraud Investigation Portal, Account Services Portal, Loan Support Portal, General Support Portal
    urgency = Column(String, default="Low")  # Low, Medium, High, Critical
    advice = Column(Text, nullable=True) # Contextual advice generated by LLM
    action_taken = Column(String, nullable=True) # Action taken by the agent
    attachment_path = Column(String, nullable=True) # Path to the uploaded image attachment
    status = Column(String, default="Pending")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
